# Generated by Django 3.2.25 on 2024-12-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=200)),
                ('number', models.BigIntegerField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('paddress', models.CharField(blank=True, max_length=200)),
                ('taddress', models.CharField(blank=True, max_length=200)),
                ('selectpradesh', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('stream', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(null=True, upload_to='')),
                ('checkbox', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
